on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@master
      - name: Install curl on Windows
        run: choco install curl
        if: matrix.os == 'windows-latest'
      - name: Install make on Windows
        run: choco install make
        if: matrix.os == 'windows-latest'
      - name: Archive
        if: matrix.os != 'windows-latest'
        run: |
          make archive
          echo "archive=$NORGANIC_ARCHIVE" >> $GITHUB_ENV
        env:
          NORGANIC_ARCHIVE: norganic-${{matrix.os}}-${{matrix.arch}}${{ matrix.os == 'windows-latest' && '.tar.gz' || '.zip' }}
      - name: Upload release 
        uses: softprops/action-gh-release@v1
        if: matrix.os != 'windows-latest'
        with:
          files: ${{ env.archive }}
          tag_name: ${{github.event.release.tag_name}}
          name: ${{github.event.release.name}}
