on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Pkg.add("PackageCompiler")
      run: julia -e 'using Pkg; Pkg.add("PackageCompiler")'
    - name: Compile
      run: julia -e 'create_app("..", "norganic")'
    - name: Archive
      run: tar -cvzf norganic.tar.gz norganic
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'norganic.tar.gz'
