on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.8'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
        arch:
          - x64
    steps:
    - uses: actions/checkout@master
    - name: Pkg.add("PackageCompiler")
      run: julia -e 'using Pkg; Pkg.add("PackageCompiler")'
    - name: Compile
      run: julia -e 'using PackageCompiler; create_app(".", "norganic")'
    - name: Archive
      run: tar -cvzf norganic.tar.gz norganic
    - name: Upload the artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'norganic-${{matrix.os}}-${{matrix.arch}}.tar.gz'
