on:
  release:
    types: [created]
name: Handle Release
jobs:
  generate:
    name: Create release-artifacts ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} 
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@master
      - name: Install curl on Windows
        run: choco install curl
        if: matrix.os == 'windows-latest'
      - name: Install make on Windows
        run: choco install make
        if: matrix.os == 'windows-latest'
      - name: Archive
        if: matrix.os != 'windows-latest'
        run: make archive
        env:
          NORGANIC_ARCHIVE: norganic-${{matrix.os}}-${{matrix.arch}}.tar.gz
      - name: Archive on Windows
        if: matrix.os == 'windows-latest'
        run: make archive
        env:
          NORGANIC_ARCHIVE: norganic-${{matrix.os}}-${{matrix.arch}}.zip
      - name: Upload the artifacts
        if: matrix.os != 'windows-latest'
        run: make upload
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NORGANIC_ARCHIVE: norganic-${{matrix.os}}-${{matrix.arch}}.tar.gz
      - name: Upload the artifacts on Windows
        if: matrix.os == 'windows-latest'
        run: make upload
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NORGANIC_ARCHIVE: norganic-${{matrix.os}}-${{matrix.arch}}.zip
